title: Blog
author: stanley
subtitle: A simple blog for interesting things I've learned about

url: "https://stanleyy3.github.io"
baseurl: ""

footer_only_homepage: true
footer_text: "Stanley Yin"

profile-picture: assets/sunny_stanley.jpg
favicon_location: assets/sunny_stanley.jpg

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
    - name: "About"
      link: "about/"
