title: Stanley's Blog
author: stanley
subtitle: Interested in a lot of things

url: "https://rahulbothra.com"
baseurl: "/blog"

footer_only_homepage: true
footer_url: "https://github.com/rhl-bthr"
footer_text: "Theme by rhl-bthr"

profile-picture: assets/sunny_stanley.jpg
favicon_location: assets/sunny_stanley.jpg

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
